server:
  port: 8083

spring:
  application:
    name: front-api-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# JWT Configuration (RG_3 - Validité 1 heure)
jwt:
  secret: ${JWT_SECRET:ebank-secret-key-very-long-and-secure-minimum-512-bits}
  expiration: 3600000
