server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Route Auth (PUBLIC - sans JWT)
        - id: auth-route
          uri: lb://front-api-service
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /auth/${segment}

        # Route vers Front-API Service protégées
        - id: front-api-protected
          uri: lb://front-api-service
          predicates:
            - Path=/api/dashboard/**,/api/operations/**
          filters:
            - JwtAuthenticationFilter

        # Route vers Customer Service
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api/customers/(?<segment>.*), /customers/${segment}
            - JwtAuthenticationFilter

        # Route vers Account Service
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/accounts/**
          filters:
            - RewritePath=/api/accounts/(?<segment>.*), /accounts/${segment}
            - JwtAuthenticationFilter

        # Route vers Operations
        - id: operations-route
          uri: lb://account-service
          predicates:
            - Path=/api/operations/**
          filters:
            - RewritePath=/api/operations/(?<segment>.*), /operations/${segment}
            - JwtAuthenticationFilter

# JWT pour validation au niveau Gateway
jwt:
  secret: ${JWT_SECRET:ebank-secret-key-very-long-and-secure-minimum-512-bits}
