server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Route vers Front-API Service - Point d'entrée unique pour toutes les API
        # Option 1: Tout passe par le BFF (Backend For Frontend)
        - id: front-api-service
          uri: lb://front-api-service
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}

# JWT pour validation au niveau Gateway
jwt:
  secret: ${JWT_SECRET:ebank-secret-key-very-long-and-secure-minimum-512-bits}
